CREATE TABLE IF NOT EXISTS projects (
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name text NOT NULL CHECK (name <> ''),
    priority integer NOT NULL,
    description text,
    deliverydate date NOT NULL
);

CREATE TABLE IF NOT EXISTS tasks (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name text NOT NULL CHECK (name <> ''),
    done BOOLEAN,
    projectId INTEGER REFERENCES projects(id)
);

-- list al tables
\dt

-- list all data in projects table
SELECT * FROM projects;

-- INSERT TEST DATA FOR projects
INSERT INTO projects(name, priority, description, deliverydate)
    VALUES ('sabaneta', 1, 'cedula', '2019-05-12');

INSERT INTO projects(name, priority, description, deliverydate)
    VALUES ('medellin', 1, 'nit', '2019-05-12');

INSERT INTO projects(name, priority, description, deliverydate)
    VALUES ('bello', 2, 'cedula', '2019-05-12');

-- INSERT TEST DATA FOR tasks
INSERT INTO tasks(name, done, projectId)
    VALUES('baldio', false, 1);

INSERT INTO tasks(name, done, projectId)
    VALUES('habitado', false, 1);

INSERT INTO tasks(name, done, projectId)
    VALUES('habitado', false, 2);

INSERT INTO tasks(name, done, projectId)
    VALUES('habitado', false, 2);

select * from tasks;

select * from tasks where projectId = 1;